export interface Guild {
    id: string
    name: string
    icon?: any
    features: any[]
    commands: any[]
    members: string[]
    channels: string[]
    bans: any[]
    roles: string[]
    stageInstances: any[]
    invites: any[]
    scheduledEvents: any[]
    shardId: number
    splash?: any
    banner?: any
    description?: any
    verificationLevel: string
    vanityURLCode?: any
    nsfwLevel: string
    premiumSubscriptionCount: number
    discoverySplash?: any
    memberCount: number
    large: boolean
    premiumProgressBarEnabled: boolean
    applicationId?: any
    afkTimeout: number
    afkChannelId?: any
    systemChannelId: string
    premiumTier: string
    explicitContentFilter: string
    mfaLevel: string
    joinedTimestamp: number
    defaultMessageNotifications: string
    systemChannelFlags: number
    maximumMembers: number
    maximumPresences?: any
    approximateMemberCount?: any
    approximatePresenceCount?: any
    vanityURLUses?: any
    rulesChannelId?: any
    publicUpdatesChannelId?: any
    preferredLocale: string
    ownerId: string
    emojis: string[]
    stickers: any[]
    createdTimestamp: number
    nameAcronym: string
    iconURL?: any
    splashURL?: any
    discoverySplashURL?: any
    bannerURL?: any
}
